---
# https://github.com/stereolabs/zed-ros2-wrapper
- ros_topic_name: <robot_namespace><device_namespace>/zed_node/rgb/camera_info
  gz_topic_name: <robot_namespace><device_namespace>/zed_node/rgb/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: ignition.msgs.CameraInfo
  lazy: true

- ros_topic_name: <robot_namespace><device_namespace>/zed_node/rgb/image_rect_color
  gz_topic_name: <robot_namespace><device_namespace>/zed_node/rgb/image_rect_color
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: ignition.msgs.Image
  lazy: true

- ros_topic_name: <robot_namespace><device_namespace>/zed_node/camera_info
  gz_topic_name: <robot_namespace><device_namespace>/zed_node/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: ignition.msgs.CameraInfo
  lazy: true

- ros_topic_name: <robot_namespace><device_namespace>/zed_node/depth
  gz_topic_name: <robot_namespace><device_namespace>/zed_node/depth
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: ignition.msgs.Image
  lazy: true

- ros_topic_name: <robot_namespace><device_namespace>/zed_node/depth/points
  gz_ros_topic_name: <robot_namespace><device_namespace>/zed_node/depth/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: ignition.msgs.PointCloudPacked
  lazy: true
