<?xml version="1.0"?>
<robot name="limo_xacro" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="limo_wheel" params="parent_prefix wheel_prefix reflect *joint_pose visual_on:=true fixed_on:=false">
        <link name="${wheel_prefix}_wheel_link">
            <inertial>
                <origin xyz="0 ${wheel_length/2} 0" rpy="1.57 0 0" />
                <mass value="0.5" />
                <inertia ixx="0.00033749999999999996" ixy="0" ixz="0" iyy="0.00033749999999999996" iyz="0" izz="0.00050625" />
            </inertial>
            <xacro:if value="${visual_on}">
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0" />
                    <geometry>
                        <mesh filename="package://limo_description/meshes/limo_optimal_wheels.dae" />
                        <!-- <mesh filename="file://$(find limo_description)/meshes/limo_optimal_wheels.dae" /> -->
                    </geometry>
                </visual>
            </xacro:if>
            <collision>
              <origin xyz="0 ${wheel_length/2} 0" rpy="1.57 0 0" />
              <geometry>
                  <cylinder length="${wheel_length}" radius="0.044" />
              </geometry>
            </collision>
        </link>

        <!-- Conditionally set the joint type -->
        <xacro:if value="${fixed_on}">
            <joint name="${wheel_prefix}_wheel" type="fixed">
                <parent link="${parent_prefix}"/>
                <child link="${wheel_prefix}_wheel_link"/>
                <xacro:insert_block name="joint_pose"/>
            </joint>
        </xacro:if>
        <!-- <xacro:unless value="${fixed_on}">
            <joint name="${wheel_prefix}_wheel" type="continuous">
                <parent link="${parent_prefix}"/>
                <child link="${wheel_prefix}_wheel_link"/>
                <xacro:insert_block name="joint_pose"/>
                <axis xyz="0 ${reflect*1} 0"/>
                <limit effort="1.5" velocity="30.0" lower="-3.14" upper="3.14"/>
                <dynamics damping="0.001" friction="0.001" />
            </joint>
        </xacro:unless> -->
        <xacro:unless value="${fixed_on}">
            <joint name="${wheel_prefix}_wheel" type="continuous">
                <parent link="${parent_prefix}"/>
                <child link="${wheel_prefix}_wheel_link"/>
                <xacro:insert_block name="joint_pose"/>
                <axis xyz="0 ${reflect*1} 0"/>
                <limit effort="20.0" velocity="10.0"/>
            </joint>
        </xacro:unless>

            
    </xacro:macro>

    <!-- New macro for center wheel with different radius -->
    <xacro:macro name="limo_center_wheel" params="parent_prefix wheel_prefix reflect *joint_pose visual_on:=true fixed_on:=false">
        <link name="${wheel_prefix}_wheel_link">
            <inertial>
                <origin xyz="0 ${wheel_length/2} 0" rpy="1.57 0 0" />
                <mass value="0.5" />
                <inertia ixx="0.00033749999999999996" ixy="0" ixz="0" iyy="0.00033749999999999996" iyz="0" izz="0.00050625" />
            </inertial>
            <xacro:if value="${visual_on}">
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0" />
                    <geometry>
                        <mesh filename="package://limo_description/meshes/limo_optimal_wheels.dae" />
                    </geometry>
                </visual>
            </xacro:if>
            <collision>
              <origin xyz="0 ${wheel_length/2} 0" rpy="1.57 0 0" />
              <geometry>
                  <cylinder length="${wheel_length}" radius="${center_wheel_radius}" />
              </geometry>
            </collision>
        </link>

        <!-- Conditionally set the joint type -->
        <xacro:if value="${fixed_on}">
            <joint name="${wheel_prefix}_wheel" type="fixed">
                <parent link="${parent_prefix}"/>
                <child link="${wheel_prefix}_wheel_link"/>
                <xacro:insert_block name="joint_pose"/>
            </joint>
        </xacro:if>
        <!-- <xacro:unless value="${fixed_on}">
            <joint name="${wheel_prefix}_wheel" type="continuous">
                <parent link="${parent_prefix}"/>
                <child link="${wheel_prefix}_wheel_link"/>
                <xacro:insert_block name="joint_pose"/>
                <axis xyz="0 ${reflect*1} 0"/>
                <limit effort="1.5" velocity="30.0" lower="-3.14" upper="3.14"/>
                <dynamics damping="0.001" friction="0.001" />
            </joint>
        </xacro:unless> -->
        <xacro:unless value="${fixed_on}">
            <joint name="${wheel_prefix}_wheel" type="continuous">
                <parent link="${parent_prefix}"/>
                <child link="${wheel_prefix}_wheel_link"/>
                <xacro:insert_block name="joint_pose"/>
                <axis xyz="0 ${reflect*1} 0"/>
                <limit effort="20.0" velocity="10.0"/>
            </joint>
        </xacro:unless>
    </xacro:macro>


    <xacro:macro name="limo_laser" params="parent_prefix frame_prefix *joint_pose">
        <link name='${frame_prefix}_link'>
            <pose>0 0 0 0 0 0</pose>
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0.0 0 0" rpy="0 0 0"/>
                <inertia
                    ixx="1e-6" ixy="0" ixz="0"
                    iyy="1e-6" iyz="0"
                    izz="1e-6"
                />
            </inertial>
            <visual name='laser_visual'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="0.02" length="0.01"/>
                </geometry>
            </visual>
            <collision name='laser_collision'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="0.032" length="0.016"/>
                </geometry>
            </collision>
        </link>
        <joint type="fixed" name="laser_joint">
            <xacro:insert_block name="joint_pose"/>
            <child link="${frame_prefix}_link"/>
            <parent link="${parent_prefix}"/>
        </joint>
        <gazebo reference="${frame_prefix}_link">
            <material>Gazebo/Yellow</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="limo_depth_camera" params="parent_prefix frame_prefix *joint_pose">
        <link name='${frame_prefix}_link'>
            <pose>0 0 0 0 0 0</pose>
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0.0 0 0" rpy="0 0 0"/>
                <inertia
                    ixx="1e-6" ixy="0" ixz="0"
                    iyy="1e-6" iyz="0"
                    izz="1e-6"
                />
            </inertial>
            <!-- <visual name='depth_camera_visual'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.06 0.015"/>
                </geometry>
            </visual> -->
            <collision name='depth_camera_collision'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.06 0.015"/>
                </geometry>
            </collision>

        </link>
    
        <joint type="fixed" name="depth_camera_joint">
            <xacro:insert_block name="joint_pose"/>
            <child link="${frame_prefix}_link"/>
            <parent link="${parent_prefix}"/>
        </joint>
        <link name="depth_link"></link>

        <joint name="${frame_prefix}_to_camera_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2} "/>
            <parent link="${frame_prefix}_link"/>
            <child link="depth_link"/>
          </joint>

        <gazebo reference="${frame_prefix}_link">
            <material>Gazebo/Yellow</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="limo_imu" params="parent_prefix frame_prefix  *joint_pose">
        <link name='${frame_prefix}_link'>
            <pose>0 0 0 0 0 0</pose>
            <inertial>
                <mass value="0.01"/>
                <origin xyz="0.0 0 0" rpy="0 0 0"/>
                <inertia
                    ixx="1e-7" ixy="0" ixz="0"
                    iyy="1e-7" iyz="0"
                    izz="1e-7"
                />
            </inertial>
            <visual name='imu_visual'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <collision name='imu_collision'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.001 0.001 0.001"/>
                </geometry>
            </collision>
        </link>
        <joint type="fixed" name="imu_joint">
            <xacro:insert_block name="joint_pose"/>
            <child link="${frame_prefix}_link"/>
            <parent link="${parent_prefix}"/>
        </joint>
        <gazebo reference="${frame_prefix}_link">
            <material>Gazebo/Yellow</material>
        </gazebo>
    </xacro:macro>
</robot>
